thunderbird/ews-rs

.github/workflows/ci.yaml

Adds a simple workflow for PR checking and pushes on `main` to ensure that `fmt` has been run, all test suites complete, and that clippy is happy.

Add GitHub CI workflow

---

Cargo.lock
Cargo.toml
src/lib.rs
src/types/common.rs
src/types/soap.rs

Exchange will return a `soap:Fault` when there is an error at the request level (rather than at the operation level). We want to return this as an error which can be inspected by the consumer.

Add support for parsing soap:Fault in error responses

---

Cargo.lock
Cargo.toml
src/lib.rs
src/types.rs
src/types/common.rs
src/types/get_folder.rs
src/types/get_item.rs
src/types/soap.rs
src/types/sync_folder_hierarchy.rs
src/types/sync_folder_items.rs

The Item type only currently has support for Messages, so GetItem requests for non-Message items will fail during deserialization.
This is still missing a fair bit of documentation.

Add support for `SyncFolderItems` and partial support for `GetItem`

---

Cargo.lock
Cargo.toml
src/types/common.rs

Prerequisite to support sending messages, since [`CreateItem`](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/createitem-operation-email-message) uses the same `Message` type as `GetItem`. Note that this makes `Message::item_id` an `Option`, since we don't have an Exchange ID yet when sending.
Requires https://github.com/thunderbird/xml-struct-rs/pull/7, https://github.com/thunderbird/xml-struct-rs/pull/8 (hence CI failing)

Support serializing Message

---

src/types.rs
src/types/common.rs
src/types/create_item.rs
src/types/get_item.rs

This change undoes part of https://github.com/thunderbird/ews-rs/pull/10 following complications from making the item ID optional. See https://phabricator.services.mozilla.com/D211258 for more context.
Instead of using `common::Message` for both serialization and deserialization, this change introduces a new `Message` type that is specific to the `CreateItem` operation. For now we agreed on only adding the fields that Thunderbird uses, but ultimately `create_item::Message` should include every field that `common::Message` does.

Add types for CreateItem

---

src/types/common.rs

Required to use the struct update syntax (with `..Default:default()`) on `Mailbox` in https://phabricator.services.mozilla.com/D212838
At some point we might want to go and audit the types in this crate to eagerly derive more std traits for them.

Derive the `Default` trait for `Mailbox`

---

Cargo.lock
Cargo.toml

We do not pin the Rust version used in CI. When 1.80.0 was stabilized, CI began failing due to an error in `time` 0.3.23. Bumping to 0.3.36 (the current Firefox minimum) solves this issue.

Bump minimum time version to avoid build failure with Rust 1.80+

---

src/types/create_item.rs

Looks like this was missed in #11 when we switched to a send-only type for `Message`, rather than re-use the one in `common.rs`. Bit scary that it has gone undiscovered for so long.

Use the types namespace prefix in CreateItem's Message type

---

src/types/create_item.rs

This is something that I changed in #15 because I assumed it would always be mandatory. After reading the documentation again, I realised it's only the case for message items.

Turn `MessageDisposition` back into an `Option`

---

src/types/common.rs
src/types/create_item.rs
src/types/update_item.rs

This proposes a series of updates to Toby's PR at https://github.com/thunderbird/ews-rs/pull/18 to more rapidly illustrate what I'm expecting.

Update documentation and get rid of serialize-only Message type

---

src/types/common.rs
src/types/operations.rs
src/types/soap.rs

We have the `name()` function as part of `sealed::EnvelopeBodyContents` already, but we don't want to unseal that to expose the function. We can, however, make it available as part of the `Operation` impl.

Expose `name()` on `Operation` to allow for debugging

---

src/types.rs
src/types/delete_item.rs

Implements the types necessary to support the `DeleteItem` operation: https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/deleteitem-operation

Add types for `DeleteItem`

---

src/types/common.rs
src/types/update_item.rs

I made some changes to support the serialization. If you don't like the enum approach, could you play around and see if there's a better way? I'll put up the changes in c-c so you can bring both down to play.

Support XML serialization for UpdateItem

---

src/types/common.rs

https://github.com/thunderbird/ews-rs/pull/23 updated `CreateItem` to use the same `Message` type for both serialization and deserialization. However, it did not add the attributes that xml-struct-rs uses to correctly include the prefix for the `t`/`types` namespace on relevant tags.
This change updates all of the fields under `Message`, so future developments aren't bitten by this error.
According to https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/createitem-operation-email-message#createitem-request-example, both the `Message` and its children need the `t` prefix.

Add the correct namespace prefixes for serialization to `Message`

---

src/types/operations.rs

Looks like an oversight from #22. Retrieving the name from an operation should be done as `op.name()`; using an associated function would mean we'd need to call e.g. `GetItem::name()`, which would make the method a bit redundant.

Make `Operation::name()` a method rather than an associated function

---

src/types/get_folder.rs

Consumers can't presently distinguish between error types. For the Thunderbird case, we request folders by distinguished ID knowing that not all of them may be present on the server. We should be checking that the error we receive in these cases is `ErrorFolderNotFound`.

Add response code field to GetFolder response

---

src/types/common.rs

`ResponseCode` is no longer `String`-based, so we can use `Copy`. It might also make sense to provide a default value of `NoError` for cases where it might be the contents of an `Option`.

Derive additional useful traits for ResponseCode

---

src/types/common.rs
src/types/create_folder.rs
src/types/get_folder.rs
src/types/soap.rs

Serialization of `CreateFolder` and deserialization of `CreateFolderResponse` were incorrect due to unspecified namespace prefixes on the `Folder` enum and use of the incorrect type in the response struct.

Correct Folder namespaces and CreateFolderResponse structure

---

src/types/sync_folder_hierarchy.rs

The `Delete` variant incorrectly omitted the field name for the contained folder ID.

Correct structure of SyncFolderHierarchy Changes for delete

---

src/types/common.rs

This is needed for https://bugzilla.mozilla.org/show_bug.cgi?id=1956601

Add support for the References property on Message items

---

src/lib.rs
src/types.rs
src/types/server_version.rs
src/types/soap.rs
src/types/soap/de.rs

This change adds some types to the `soap` module to support SOAP headers, as well as a couple of types to represent SOAP headers related to Exchange Server version handling (for [bug 1964652](https://bugzilla.mozilla.org/show_bug.cgi?id=1964652)).
I wasn't entirely sure how to structure SOAP headers, so let me know if there's any improvement that could be made there. Although it's worth noting https://github.com/thunderbird/xml-struct-rs/issues/9 limits the ways to represent request headers.

Support server version headers

---

src/types/soap.rs

Broke in https://github.com/thunderbird/ews-rs/pull/44. The CI didn't catch it because GitHub automatically disabled it due to low activity on this repository.

Fix broken deserialization test

---

.github/CODEOWNERS
README.md
clippy.toml

- Some documentation updates
- Establish the tested MSRV and explain influence by Firefox Rust Update Policy
- Add COCDEOWNERS file for future branch protection work.

Docs + MSRV

---

src/types/common.rs
src/types/common/message_xml.rs
src/types/soap.rs
src/types/soap/de.rs

This is an extensive change to how `MessageXml` works, and loses the ability to store the raw XML within the type (most attributes in particular will now be implicitly stripped, as will new fields in known types). This change allows `MessageXml` as a member in other types that derive `Deserialize`.
First half of addressing [Bug 1971330](https://bugzilla.mozilla.org/show_bug.cgi?id=1971330).
Feel free to point me down an entirely different approach, or delve into all the nits, this was in large part a learning exercise (serde *really* doesn't want you parsing unknown types). :)

implement `Deserialize` for `MessageXml`

---

src/types/get_folder.rs
src/types/soap.rs
src/types/soap/de.rs

Serde considers attributes as nested elements. So if the soap body tag has attributes on it, our parsing code fail because we expect the operation response to be the only element in there.

Ignore attributes on soap bodies

---

README.md

Very minor, but [best accessibility practices](https://www.w3.org/TR/WCAG10-HTML-TECHS/#link-text) are to avoid "here" links. Also fix the link to the license file for GitHub's rendering.

README.md nits

---

.github/workflows/ci.yaml
src/types/common/message_xml.rs

Realized I didn't check `cargo doc` after moving items to a new file in the last PR, which broke some links. This fixes that, and adds a few improvements to the CI to prevent that sort of mistake going forward.

check docs in CI

---

ews/src/types/operations.rs
ews/src/types/soap.rs
ews/src/types/soap/de.rs
ews_proc_macros/src/lib.rs

This presumably optimizes into the same thing, but using associated constants removes a layer of indirection and allows us to use the name in more places (notably, as compile-time constants in other types or methods).

Replace `name()`s with associated NAME constants.
